festa/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from models import Convidado


class NovoConvidadoForm(FlaskForm):

    nome = StringField('Nome do convidado',
                            validators=[DataRequired(), Length(min=3, max=50)])
    acomp = StringField('Número de acompanhantes')
    enviar = SubmitField('enviar')

    def __init__(self, nome_original=None, *args, **kwargs):
        super(NovoConvidadoForm, self).__init__(*args, **kwargs)
        self.nome_original = nome_original

festa/__init__.py
from flask import Blueprint

bp = Blueprint('festa', __name__, template_folder='templates')

from festa import routes

festa/routes.py
from models import convidado
from flask import render_template, redirect, url_for, flash, request
from festa import bp
from festa.forms import NovoConvidadoForm
from models import Convidado
from app import db


@bp.route('/')
def conv():
    form = NovoConvidadoForm()
    convidados = Convidado.query.all()
    return render_template('festa.html', convidados=convidados, 
                            title='Festa', form=form)


@bp.route('/', methods=['GET', 'POST'])
def create():
    form = NovoConvidadoForm()
    if form.validate_on_submit():
        convidado = Convidado(nome=form.nome.data, acompanhante=form.acomp.data)
        db.session.add(convidado)
        db.session.commit()
        return redirect(url_for('festa.conv'))
    return render_template('festa.html', title='Festa', form=form)

@bp.route('/<int:id>', methods=['GET', 'POST'])
def update(id):
    convidado = Convidado.query.get_or_404(id)
    form = NovoConvidadoForm(nome_original=convidado.nome)
    if form.validate_on_submit():
        convidado.nome = form.nome.data
        convidado.acompanhante = form.acomp.data
        db.session.add(convidado)
        db.session.commit()
        flash('Alteração salva com sucesso!!!')
        return redirect (url_for('festa.conv'))
    elif request.method == 'GET':
        convidado = Convidado.query.get(id)
        form.nome.data = convidado.nome
        form.acomp.data = convidado.acompanhante
        convidados = Convidado.query.all()
    return render_template('festa.html', convidados=convidados, 
                            form=form, title='Festa')


@bp.route('/<int:id>/delete')
def delete(id):
    convidado = Convidado.query.get_or_404(id)
    db.session.delete(convidado)
    db.session.commit()
    return redirect(url_for('festa.conv'))

festa/templates/festa.html
{% extends 'bootstrap/base.html' %}

{% block content %}


<div class="card bg-dark text-white " style="margin: 10px">
  <div class="card-heading">
    <h1 class="card-title">Lista de convidados</h1>
  </div>

  <form class="form-inline" method="post" style="margin: 20px 0" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.nome(size=32, type="text", class="form-control", placeholder="Nome") }}
			{{ form.acomp(size=32, class="form-control", placeholder="Acompanhantes") }}
			{{ form.enviar(class="btn btn-primary") }}
    </div>
  </form>

  <div class="card-body">
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Acompanhates</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for convidado in convidados %}
        <tr>
          <td>{{ convidado.nome }}</td>
          <td>{{ convidado.acompanhante }}</td>
          <td>
            <div class="btn-group d-flex justify-content-end">
              <a href="{{ url_for('festa.update', id=convidado.id) }}" class="btn btn-sm btn-primary">Editar</a>
              <a href="{{ url_for('festa.delete', id=convidado.id) }}" class="delete btn btn-sm btn-danger">Excluir</a>

            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>



<!--Input dos convidados
  <form class="form-inline" method="post" th:object="${convidado}" th:action="@{/convidados}" style="margin: 20px 0">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Nome" th:field="*{nome}" />
      <input type="text" class="form-control" placeholder="Acompanhantes" th:field="*{quantidadeAcompanhantes}" />
      <button type="submit" class="btn btn-primary">Adicionar</button>
    </div>
  </form>
  -->

{% endblock %}